version: '3.8'

services:
  flask:
    build: ./flask_app
    container_name: flask_app
    expose:
      - "5000"

  node:
    build: ./node_app
    container_name: node_app
    expose:
      - "3001"
    environment:
      - NODE_ENV=production

  next:
    build: ./next_app
    container_name: next_app
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
      - node
      - next
